apiVersion: v1
kind: Namespace
metadata:
  name: testprothameera-staging
  labels:
    environmentId: env_154af166-5cf9-4d83-a3a4-d5f14b5aff50
    projectId: project_a0e8d097-2d10-4122-bec4-41f4f61ec6d3
    projectName: testprothameera
    environmentName: staging
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
